name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    
    runs-on: ubuntu-latest

    steps:
    - uses

    - uses: actions/checkout@v3
    - name: Build the Docker image and run basic test
      run: |
        cd verilog/dv/verilatorTest
        docker run -ti verilator/verilator:latest --version
        verilator --cc --exe --build -j 0 -Wall sim_main.cpp our.v
