name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: docker://verilator/verilator:latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd verilog/dv/verilatorTest
        verilator --cc --exe --build -j 0 -Wall sim_main.cpp our.v
